// src/Data.js
export const initialData = {
  // User roles and permissions
  roles: {
    admin: {
      id: "admin",
      name: "Administrator",
      permissions: [
        "create_task",
        "edit_any_task",
        "delete_any_task",
        "manage_users",
        "manage_projects",
        "view_all",
        "assign_tasks",
        "comment_on_tasks",
        "log_time",
        "manage_team_members",
      ],
    },
    project_manager: {
      id: "project_manager",
      name: "Project Manager",
      permissions: [
        "create_task",
        "edit_project_tasks",
        "assign_tasks",
        "view_project_reports",
        "manage_project_members",
        "comment_on_tasks",
        "log_time",
        "delete_project_tasks",
      ],
    },
    team_lead: {
      id: "team_lead",
      name: "Team Lead",
      permissions: [
        "create_task",
        "edit_team_tasks",
        "assign_team_tasks",
        "view_team_reports",
        "comment_on_tasks",
        "log_time",
        "delete_team_tasks",
      ],
    },
    developer: {
      id: "developer",
      name: "Developer",
      permissions: [
        "edit_assigned_tasks",
        "comment_on_tasks",
        "log_time",
        "view_assigned",
        "create_subtasks",
      ],
    },
    viewer: {
      id: "viewer",
      name: "Viewer",
      permissions: ["view_assigned", "comment_on_tasks"],
    },
  },

  // Current logged in user (this would come from auth)
  currentUser: {
    id: "john",
    username: "john.doe",
    email: "john.doe@company.com",
    name: "John Doe",
    avatar: "👨‍💻",
    role: "admin",
    teams: ["team-1"],
    projects: ["proj-1", "proj-2"],
    isActive: true,
    joinDate: "2024-01-15",
    timezone: "America/New_York",
  },

  // Teams with enhanced information
  teams: [
    {
      id: "team-1",
      name: "Frontend Team",
      color: "#3B82F6",
      members: ["john", "sarah", "mike"],
      lead: "sarah",
      description: "Responsible for user interface and frontend development",
      createdDate: "2024-01-01",
      isActive: true,
    },
    {
      id: "team-2",
      name: "Backend Team",
      color: "#10B981",
      members: ["alex", "emma", "david"],
      lead: "alex",
      description: "Handles server-side logic and API development",
      createdDate: "2024-01-01",
      isActive: true,
    },
    {
      id: "team-3",
      name: "Design Team",
      color: "#F59E0B",
      members: ["lisa", "tom"],
      lead: "lisa",
      description: "Creates user experience and visual designs",
      createdDate: "2024-01-01",
      isActive: true,
    },
  ],

  // Projects with comprehensive details
  projects: [
    {
      id: "proj-1",
      name: "E-Commerce App",
      team: "team-1",
      progress: 65,
      status: "active",
      startDate: "2025-01-01",
      endDate: "2025-12-31",
      budget: 100000,
      description: "Complete e-commerce solution with payment integration",
      manager: "sarah",
      priority: "high",
      client: "TechCorp Inc.",
      tags: ["React", "E-commerce", "Payment"],
    },
    {
      id: "proj-2",
      name: "API Gateway",
      team: "team-2",
      progress: 80,
      status: "active",
      startDate: "2025-02-01",
      endDate: "2025-08-31",
      budget: 75000,
      description: "Centralized API gateway for microservices",
      manager: "alex",
      priority: "high",
      client: "Internal",
      tags: ["Node.js", "Microservices", "API"],
    },
    {
      id: "proj-3",
      name: "Brand Redesign",
      team: "team-3",
      progress: 45,
      status: "active",
      startDate: "2025-03-01",
      endDate: "2025-09-30",
      budget: 50000,
      description: "Complete brand identity and design system overhaul",
      manager: "lisa",
      priority: "medium",
      client: "Marketing Dept",
      tags: ["Design", "Branding", "Identity"],
    },
  ],

  // Members with detailed profiles
  members: {
    john: {
      id: "john",
      name: "John Doe",
      avatar: "👨‍💻",
      role: "admin",
      jobTitle: "Senior Frontend Developer",
      email: "john.doe@company.com",
      phone: "+1-555-0001",
      skills: ["React", "JavaScript", "TypeScript", "CSS", "Node.js"],
      hourlyRate: 75,
      isActive: true,
      department: "Engineering",
      location: "New York, NY",
      joinDate: "2023-01-15",
      manager: null,
      workingHours: {
        start: "09:00",
        end: "17:00",
        timezone: "America/New_York",
      },
    },
    sarah: {
      id: "sarah",
      name: "Sarah Wilson",
      avatar: "👩‍💻",
      role: "project_manager",
      jobTitle: "Senior React Developer & PM",
      email: "sarah.wilson@company.com",
      phone: "+1-555-0002",
      skills: ["React", "Redux", "Node.js", "Project Management", "Agile"],
      hourlyRate: 85,
      isActive: true,
      department: "Engineering",
      location: "San Francisco, CA",
      joinDate: "2023-02-01",
      manager: "john",
      workingHours: {
        start: "08:00",
        end: "16:00",
        timezone: "America/Los_Angeles",
      },
    },
    mike: {
      id: "mike",
      name: "Mike Johnson",
      avatar: "👨‍🔧",
      role: "team_lead",
      jobTitle: "DevOps Engineer",
      email: "mike.johnson@company.com",
      phone: "+1-555-0003",
      skills: ["Docker", "AWS", "Kubernetes", "CI/CD", "Terraform"],
      hourlyRate: 90,
      isActive: true,
      department: "DevOps",
      location: "Austin, TX",
      joinDate: "2023-03-01",
      manager: "john",
      workingHours: {
        start: "10:00",
        end: "18:00",
        timezone: "America/Chicago",
      },
    },
    alex: {
      id: "alex",
      name: "Alex Brown",
      avatar: "👨‍💼",
      role: "team_lead",
      jobTitle: "Senior Backend Developer",
      email: "alex.brown@company.com",
      phone: "+1-555-0004",
      skills: ["Node.js", "Python", "MongoDB", "PostgreSQL", "Redis"],
      hourlyRate: 80,
      isActive: true,
      department: "Engineering",
      location: "Seattle, WA",
      joinDate: "2023-01-20",
      manager: "john",
      workingHours: {
        start: "09:00",
        end: "17:00",
        timezone: "America/Los_Angeles",
      },
    },
    emma: {
      id: "emma",
      name: "Emma Davis",
      avatar: "👩‍💼",
      role: "developer",
      jobTitle: "API Developer",
      email: "emma.davis@company.com",
      phone: "+1-555-0005",
      skills: ["REST API", "GraphQL", "Express.js", "Testing", "Postman"],
      hourlyRate: 70,
      isActive: true,
      department: "Engineering",
      location: "Boston, MA",
      joinDate: "2023-04-15",
      manager: "alex",
      workingHours: {
        start: "09:00",
        end: "17:00",
        timezone: "America/New_York",
      },
    },
    david: {
      id: "david",
      name: "David Lee",
      avatar: "👨‍🎨",
      role: "developer",
      jobTitle: "Full Stack Developer",
      email: "david.lee@company.com",
      phone: "+1-555-0006",
      skills: ["React", "Node.js", "MongoDB", "AWS", "Docker"],
      hourlyRate: 78,
      isActive: true,
      department: "Engineering",
      location: "Denver, CO",
      joinDate: "2023-05-01",
      manager: "alex",
      workingHours: {
        start: "08:00",
        end: "16:00",
        timezone: "America/Denver",
      },
    },
    lisa: {
      id: "lisa",
      name: "Lisa Chen",
      avatar: "👩‍🎨",
      role: "team_lead",
      jobTitle: "Senior UI/UX Designer",
      email: "lisa.chen@company.com",
      phone: "+1-555-0007",
      skills: [
        "Figma",
        "Adobe Creative Suite",
        "UI/UX",
        "Prototyping",
        "User Research",
      ],
      hourlyRate: 65,
      isActive: true,
      department: "Design",
      location: "Los Angeles, CA",
      joinDate: "2023-02-15",
      manager: "john",
      workingHours: {
        start: "09:00",
        end: "17:00",
        timezone: "America/Los_Angeles",
      },
    },
    tom: {
      id: "tom",
      name: "Tom Garcia",
      avatar: "👨‍🎭",
      role: "developer",
      jobTitle: "UX Designer",
      email: "tom.garcia@company.com",
      phone: "+1-555-0008",
      skills: [
        "User Research",
        "Wireframing",
        "Sketch",
        "InVision",
        "Usability Testing",
      ],
      hourlyRate: 68,
      isActive: true,
      department: "Design",
      location: "Miami, FL",
      joinDate: "2023-06-01",
      manager: "lisa",
      workingHours: {
        start: "09:00",
        end: "17:00",
        timezone: "America/New_York",
      },
    },
  },

  // Kanban columns with permissions and limits
  columns: {
    backlog: {
      id: "backlog",
      title: "Backlog",
      color: "#6B7280",
      taskIds: ["task-1", "task-2", "task-13"],
      maxTasks: null,
      allowedRoles: ["admin", "project_manager", "team_lead"],
      description: "Ideas and requests waiting to be prioritized",
    },
    todo: {
      id: "todo",
      title: "To Do",
      color: "#3B82F6",
      taskIds: ["task-3", "task-4", "task-14"],
      maxTasks: null,
      allowedRoles: ["admin", "project_manager", "team_lead", "developer"],
      description: "Tasks ready to be worked on",
    },
    "in-progress": {
      id: "in-progress",
      title: "In Progress",
      color: "#F59E0B",
      taskIds: ["task-5", "task-6", "task-15"],
      maxTasks: 5,
      allowedRoles: ["admin", "project_manager", "team_lead", "developer"],
      description: "Tasks currently being worked on",
    },
    review: {
      id: "review",
      title: "In Review",
      color: "#8B5CF6",
      taskIds: ["task-7", "task-8"],
      maxTasks: 3,
      allowedRoles: ["admin", "project_manager", "team_lead"],
      description: "Tasks waiting for review and approval",
    },
    testing: {
      id: "testing",
      title: "Testing",
      color: "#06B6D4",
      taskIds: ["task-9", "task-10"],
      maxTasks: null,
      allowedRoles: ["admin", "project_manager", "team_lead"],
      description: "Tasks being tested for quality assurance",
    },
    done: {
      id: "done",
      title: "Done",
      color: "#10B981",
      taskIds: ["task-11", "task-12"],
      maxTasks: null,
      allowedRoles: ["admin", "project_manager", "team_lead", "developer"],
      description: "Completed tasks",
    },
  },

  // Task types and priorities
  taskTypes: [
    { id: "feature", name: "Feature", color: "#3B82F6", icon: "🆕" },
    { id: "bug", name: "Bug", color: "#EF4444", icon: "🐛" },
    { id: "improvement", name: "Improvement", color: "#10B981", icon: "⚡" },
    {
      id: "documentation",
      name: "Documentation",
      color: "#8B5CF6",
      icon: "📚",
    },
    { id: "testing", name: "Testing", color: "#F59E0B", icon: "🧪" },
    { id: "design", name: "Design", color: "#EC4899", icon: "🎨" },
    {
      id: "infrastructure",
      name: "Infrastructure",
      color: "#6B7280",
      icon: "🏗️",
    },
  ],

  priorities: [
    { id: "critical", name: "Critical", color: "#DC2626", level: 4 },
    { id: "high", name: "High", color: "#EA580C", level: 3 },
    { id: "medium", name: "Medium", color: "#CA8A04", level: 2 },
    { id: "low", name: "Low", color: "#16A34A", level: 1 },
  ],

  // Available labels/tags
  labels: [
    { id: "frontend", name: "Frontend", color: "#3B82F6" },
    { id: "backend", name: "Backend", color: "#10B981" },
    { id: "database", name: "Database", color: "#8B5CF6" },
    { id: "security", name: "Security", color: "#EF4444" },
    { id: "performance", name: "Performance", color: "#F59E0B" },
    { id: "ui-ux", name: "UI/UX", color: "#EC4899" },
    { id: "api", name: "API", color: "#06B6D4" },
    { id: "testing", name: "Testing", color: "#84CC16" },
    { id: "documentation", name: "Documentation", color: "#6B7280" },
    { id: "mobile", name: "Mobile", color: "#A855F7" },
  ],

  // Comprehensive tasks data
  tasks: {
    "task-1": {
      id: "task-1",
      title: "Setup Authentication System",
      description:
        "Implement JWT-based authentication with refresh tokens and secure session management",
      project: "proj-1",
      assignee: "alex",
      reporter: "sarah",
      priority: "high",
      type: "feature",
      status: "backlog",
      dueDate: "2025-07-20",
      createdDate: "2025-07-10T10:00:00Z",
      updatedDate: "2025-07-10T10:00:00Z",
      labels: ["backend", "security", "api"],
      storyPoints: 8,
      estimatedHours: 16,
      loggedHours: 0,
      progress: 0,
      isBlocked: false,
      blockingReason: null,
      dependencies: [],
      watchers: ["sarah", "john", "mike"],
      attachments: [
        {
          id: "attach-1",
          name: "auth-flow-diagram.png",
          url: "/files/auth-flow-diagram.png",
          type: "image",
          size: 2500000,
          uploadedBy: "sarah",
          uploadedAt: "2025-07-10T10:30:00Z",
        },
        {
          id: "attach-2",
          name: "security-requirements.pdf",
          url: "/files/security-requirements.pdf",
          type: "pdf",
          size: 1800000,
          uploadedBy: "john",
          uploadedAt: "2025-07-10T11:00:00Z",
        },
      ],
      comments: [
        {
          id: "comment-1",
          author: "sarah",
          text: "Please ensure we follow OAuth 2.0 standards and implement proper CSRF protection",
          timestamp: "2025-07-10T10:30:00Z",
          edited: false,
        },
        {
          id: "comment-2",
          author: "john",
          text: "Also consider implementing rate limiting for login attempts",
          timestamp: "2025-07-10T11:15:00Z",
          edited: false,
        },
        {
          id: "comment-3",
          author: "alex",
          text: "I will start with researching the best JWT libraries for Node.js",
          timestamp: "2025-07-10T14:20:00Z",
          edited: false,
        },
      ],
      timeEntries: [],
      checklist: [
        {
          id: "check-1",
          text: "Research JWT libraries and security best practices",
          completed: false,
          assignee: "alex",
        },
        {
          id: "check-2",
          text: "Design database schema for users and sessions",
          completed: false,
          assignee: "alex",
        },
        {
          id: "check-3",
          text: "Implement user registration endpoint",
          completed: false,
          assignee: "alex",
        },
        {
          id: "check-4",
          text: "Implement login endpoint with rate limiting",
          completed: false,
          assignee: "alex",
        },
        {
          id: "check-5",
          text: "Implement refresh token mechanism",
          completed: false,
          assignee: "alex",
        },
        {
          id: "check-6",
          text: "Add password reset functionality",
          completed: false,
          assignee: "alex",
        },
        {
          id: "check-7",
          text: "Write comprehensive tests",
          completed: false,
          assignee: "alex",
        },
      ],
      customFields: {
        "client-priority": "high",
        "business-value": "critical",
        "technical-debt": "none",
      },
    },
    "task-2": {
      id: "task-2",
      title: "Design System Documentation",
      description:
        "Create comprehensive design system documentation including components, patterns, and usage guidelines",
      project: "proj-3",
      assignee: "lisa",
      reporter: "tom",
      priority: "medium",
      type: "documentation",
      status: "backlog",
      dueDate: "2025-07-25",
      createdDate: "2025-07-08T09:00:00Z",
      updatedDate: "2025-07-09T14:20:00Z",
      labels: ["design", "documentation", "ui-ux"],
      storyPoints: 5,
      estimatedHours: 12,
      loggedHours: 0,
      progress: 0,
      isBlocked: false,
      blockingReason: null,
      dependencies: [],
      watchers: ["tom", "john", "sarah"],
      attachments: [
        {
          id: "attach-3",
          name: "design-system-template.pdf",
          url: "/files/design-system-template.pdf",
          type: "pdf",
          size: 1800000,
          uploadedBy: "tom",
          uploadedAt: "2025-07-08T10:00:00Z",
        },
      ],
      comments: [
        {
          id: "comment-4",
          author: "tom",
          text: "Include component variations and usage examples for each design token",
          timestamp: "2025-07-09T14:20:00Z",
          edited: false,
        },
        {
          id: "comment-5",
          author: "john",
          text: "Make sure to include code examples for developers",
          timestamp: "2025-07-09T15:30:00Z",
          edited: false,
        },
      ],
      timeEntries: [],
      checklist: [
        {
          id: "check-8",
          text: "Document color palette and usage",
          completed: true,
          assignee: "lisa",
        },
        {
          id: "check-9",
          text: "Document typography scale and hierarchy",
          completed: false,
          assignee: "lisa",
        },
        {
          id: "check-10",
          text: "Document spacing and layout systems",
          completed: false,
          assignee: "lisa",
        },
        {
          id: "check-11",
          text: "Document component library",
          completed: false,
          assignee: "lisa",
        },
        {
          id: "check-12",
          text: "Create usage guidelines and examples",
          completed: false,
          assignee: "lisa",
        },
        {
          id: "check-13",
          text: "Review and approve with stakeholders",
          completed: false,
          assignee: "tom",
        },
      ],
      customFields: {
        "design-review": "pending",
        "stakeholder-approval": "pending",
      },
    },
    // Add more tasks following the same pattern...
  },

  // System activity log
  activityLog: [
    {
      id: "activity-1",
      type: "task_created",
      user: "sarah",
      timestamp: "2025-07-17T09:30:00Z",
      details: {
        taskId: "task-1",
        taskTitle: "Setup Authentication System",
      },
    },
    {
      id: "activity-2",
      type: "task_assigned",
      user: "sarah",
      timestamp: "2025-07-17T10:15:00Z",
      details: {
        taskId: "task-1",
        assignee: "alex",
        previousAssignee: null,
      },
    },
    {
      id: "activity-3",
      type: "comment_added",
      user: "john",
      timestamp: "2025-07-17T11:20:00Z",
      details: {
        taskId: "task-1",
        commentId: "comment-2",
      },
    },
  ],

  // Application settings and configurations
  settings: {
    workingDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    defaultWorkingHours: 8,
    timeTrackingEnabled: true,
    notificationsEnabled: true,
    autoAssignEnabled: false,
    sprintDuration: 14, // days
    estimationMethod: "story_points", // or 'hours'
    boardLayout: "kanban", // or 'scrum'
    customFields: {
      "client-priority": {
        type: "select",
        options: ["low", "medium", "high", "critical"],
        required: false,
      },
      "business-value": {
        type: "select",
        options: ["low", "medium", "high", "critical"],
        required: false,
      },
      "technical-debt": {
        type: "select",
        options: ["none", "minor", "major", "critical"],
        required: false,
      },
    },
  },

  // Notification system
  notifications: [
    {
      id: "notif-1",
      type: "task_assigned",
      recipient: "alex",
      message: "You have been assigned to task: Setup Authentication System",
      read: false,
      timestamp: "2025-07-17T10:15:00Z",
      link: "/tasks/task-1",
    },
    {
      id: "notif-2",
      type: "task_due_soon",
      recipient: "alex",
      message: 'Task "Setup Authentication System" is due in 3 days',
      read: false,
      timestamp: "2025-07-17T12:00:00Z",
      link: "/tasks/task-1",
    },
  ],
};
